### ISSUE TITLE
Geographic availability

### ISSUE THREAD

**Issue by OriKatz1** [ChandlerLutz/LandUnavailabilityData#1]
Hi,
I downloaded the zip-level Zillow estimates, but they only exist for the Northeast - is it a mistake? couldn't find anything about a limitation like that in the paper.

Thanks

**Comment by ChandlerLutz** [comment]
Which file in particular are you looking at? 

I'm seeing over 15k zip codes for the "from 2002" total cross-section, [here](https://www.dropbox.com/sh/kinpoyc2z07v9vx/AABZPE5Tdrxvn8_n_IfRhORma/best-lu-for-zillow-hp?dl=0&preview=12-zip_data_from_2002_lu_total_ml_best.csv&subfolder_nav_tracking=1) and over 23k zip codes for the "from 2011" total cross-section, [here](https://www.dropbox.com/sh/kinpoyc2z07v9vx/AABZPE5Tdrxvn8_n_IfRhORma/best-lu-for-zillow-hp?dl=0&preview=16-zip_data_from_2011_lu_total_ml_best.csv&subfolder_nav_tracking=1).

**Comment by OriKatz1** [comment]
Since I wanted a panel of zip-level data, I downloaded "15-zip_data_from_2011_lu_panel_ml_best.csv", and there I see about 3,000 zips for each year. 
Looking again at the data I think that this is my mistake in the uploading process of the data.

**Comment by ChandlerLutz** [comment]
Hmm... when I download the that data and read it in with the below code, I get 23,094 unique zips. Maybe your file was corrupted on download? BTW, that file is 109 MB after download, if that helps. 

```r 
library(data.table)
DT <- fread("./15-zip_data_from_2011_lu_panel_ml_best.csv")
DT[, uniqueN(zip)]

# [1] 23094
```

![image](https://user-images.githubusercontent.com/2385415/161749226-d81ce553-652d-478a-99f9-6898c0d53c34.png)

**Comment by ChandlerLutz** [comment]
Closing as the data seem correct. Please re-open if you have any issues.
